from entsoe_client.Utils.ParameterEnum import ParameterEnum


class DocumentType(str, ParameterEnum):
    A09 = ("Finalised schedule",)
    A11 = ("Aggregated energy data report",)
    A15 = ("Acquiring system operator reserve schedule",)
    A24 = ("Bid document",)
    A25 = ("Allocation result document",)
    A26 = ("Capacity document",)
    A31 = ("Agreed capacity",)
    A38 = ("Reserve allocation result document",)
    A44 = ("Price Document",)
    A61 = ("Estimated Net Transfer Capacity",)
    A63 = ("Redispatch notice",)
    A65 = ("System total load",)
    A68 = ("Installed generation per document_type",)
    A69 = ("Wind and solar forecast",)
    A70 = ("Load forecast margin",)
    A71 = ("Generation forecast",)
    A72 = ("Reservoir filling information",)
    A73 = ("Actual generation",)
    A74 = ("Wind and solar generation",)
    A75 = ("Actual generation per document_type",)
    A76 = ("Load unavailability",)
    A77 = ("Production unavailability",)
    A78 = ("Transmission unavailability",)
    A79 = ("Offshore grid infrastructure unavailability",)
    A80 = ("Generation unavailability",)
    A81 = ("Contracted reserves",)
    A82 = ("Accepted offers",)
    A83 = ("Activated balancing quantities",)
    A84 = ("Activated balancing prices",)
    A85 = ("Imbalance prices",)
    A86 = ("Imbalance volume",)
    A87 = ("Financial situation",)
    A88 = ("Cross border balancing",)
    A89 = ("Contracted reserve prices",)
    A90 = ("Interconnection network expansion",)
    A91 = ("Counter trade notice",)
    A92 = ("Congestion costs",)
    A93 = ("DC link capacity",)
    A94 = ("Non EU allocations",)
    A95 = ("Configuration document",)
    B11 = "Flow - based allocations"
