name: Python package
on:
  workflow_dispatch
jobs:
  build-testpypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to test pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          python_version: "3.9"
          poetry_version: "==1.1.7" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
          build_format: "sdist"
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          ignore_dev_requirements: "yes"
  build-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.8
        with:
          python_version: "3.9"
          poetry_version: "==1.1.7" # (PIP version specifier syntax)
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          build_format: "sdist"
